### ISSUE TITLE
Revisión de README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-chkr_s-l#1]
Hola.
He revisado el README, tanto el contenido como el formato. 

- Hay algunas líneas del texto que debéis eliminar (son restos de la plantilla).
- El proyecto es adecuado. Os sugiero la utilización de la librería SDL. Podéis revisar lo que hicieron unos compañeros del curso pasado: [código](https://github.com/aigora/twE105_1920-los_otros) y [wiki](https://github.com/aigora/twE105_1920-los_otros/wiki)

**Comment by Vegely** [comment]
He estado intentando aprender un poco a usar la librería SDL y si no me equivoco funciona solo en C++, ¿Me estoy equivocando o se puede hacer también para C?

**Comment by oscarperpinan** [comment]
También funciona con C. Echa un vistazo al trabajo del curso pasado que os recomendé.
