### ISSUE TITLE
Manejo de GitHub

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-chkr_s-l#10]
Algunos comentarios para que mejoréis el uso de GitHub:

- Los mensajes de commit deben ser útiles. No os limitéis a poner mensajes obvios como "cambios" o irrelevantes como "1".
- No sincronicéis archivos auxiliares. Los ficheros .layout, o .drawio no deberían estar en el repositorio.

**Comment by Vegely** [comment]
El problema esta en que a veces cuando me meto en github desktop algunos cambios son porque se cambia el mouse de sitio o algo por el estilo y no se como hacer para que git no recoja los cambios.

**Comment by oscarperpinan** [comment]
Para eso está el fichero .gitignore. En las diapositivas de Introduction a GitHub hay un enlace a la documentación de este fichero.

**Comment by Vegely** [comment]
Solucionado el problema de commits poco informativos
